# Generated by Django 5.2.12 on 2026-03-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown Track', max_length=255)),
                ('artist', models.CharField(blank=True, default='', max_length=255)),
                ('album', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file', models.FileField(upload_to='tracks/')),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('youtube', 'YouTube')], default='upload', max_length=10)),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('youtube_id', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
