# Generated by Django 5.2.12 on 2026-03-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyrics_lrc',
            field=models.TextField(blank=True, default='', help_text='Cached LRC synced lyrics'),
        ),
    ]
