# Generated by Django 5.2.12 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_track_lyrics_lrc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='youtube_url',
            new_name='source_url',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='youtube_id',
            new_name='source_identifier',
        ),
        migrations.AddField(
            model_name='track',
            name='playback_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='source',
            field=models.CharField(
                choices=[
                    ('upload', 'Upload'),
                    ('soundcloud', 'SoundCloud'),
                    ('internet_archive', 'Internet Archive'),
                    ('remote_url', 'Remote URL'),
                    ('youtube', 'YouTube (Legacy)'),
                ],
                default='upload',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='track',
            name='source_identifier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
