# Generated by Django 5.2.12 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_track_remote_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview_only',
            field=models.BooleanField(default=False),
        ),
    ]
